### PR TITLE
Migrations

### PR DESCRIPTION
**Pull request by bonnzer**
* added migrations with [migrate](https://www.npmjs.com/package/migrate)
* set `node` version 12.x and higher

### CODE REVIEW

**Comment by melvynkim** [comment]
Unsure if we can work with the `migrate`

**Comment by melvynkim** [comment]
@bonnzer 

Can we add these default users in an organized file structure, so we can add these as the importer from the database?

We can use in CSV format with the following columns:

```username,

**Comment by melvynkim** [comment]
The CSVs can be:

**Comment by bonnzer** [comment]
@melvynkim yes we can, but it's not convenient. Usually migration file is the storage for all needed migrations. But, again, we can =)

**Pull request closed without merging**
